### ISSUE TITLE
href from egghead.io

### ISSUE THREAD

**Issue by ShMcK** [kentcdodds/webpack-angular#1]
The href to here from egghead.io is pointing to:
`https://github.com/eggheadio/https://github.com/kentcdodds/webpack-angular/issues/new`

**Comment by ShMcK** [comment]
To be clear, coming from `https://egghead.io/lessons/angularjs-angular-with-webpack-testing-with-karma-mocha-and-chai`

**Comment by kentcdodds** [comment]
I need to give you an apology. For some reason, I want watching this repository so I want getting notifications about issues and pull requests. I am so incredibly sorry. Please forgive me. I really feel awful. I hope my unresponsiveness doesn't hinder you contributing more in the future.

As for your specific pull request, I'll give it a closer look soon.

**Comment by kentcdodds** [comment]
I think it's been fixed now. Again, I apologize for not responding sooner than 10 months :-/

**Comment by ShMcK** [comment]
No worries, I had totally forgotten about this. But really no need to apologize when you're doing great work for the community. We all appreciate your efforts.
